CREATE TABLE IF NOT EXISTS Bingo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  channelId TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS BingoItems (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  `index` INTEGER NOT NULL,
  bingoId INTEGER NOT NULL,
  text TEXT NOT NULL,
  isMarked BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY(bingoId) REFERENCES Bingo(id)
);

CREATE TABLE IF NOT EXISTS Tokens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  accessToken TEXT NOT NULL,
  teamId INTEGER NOT NULL,
  teamName TEXT
);