CREATE TABLE IF NOT EXISTS Bingo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  channelId TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BingoItems (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  `index` INTEGER NOT NULL,
  bingoId INTEGER NOT NULL,
  text TEXT NOT NULL,
  isMarked BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY(bingoId) REFERENCES Bingo(id)
);